export const GET_FILE_LIST = 'GET_FILE_LIST';
export const UPDATE_FILE_LIST = 'UPDATE_FILE_LIST';

export const REQUEST_FILE_LIST = 'REQUEST_FILE_LIST';
export const RECEIVE_FILE_LIST_SUCCESS = 'RECEIVE_FILE_LIST_SUCCESS';
export const SELECT_FILE_TYPE = 'SELECT_FILE_TYPE';

export const REQUEST_DELETE_FILE = 'REQUEST_DELETE_FILE';
export const RECEIVE_DELETE_FILE_SUCCESS = 'RECEIVE_DELETE_FILE_SUCCESS';

export const REQUEST_UPLOAD_FILE = 'REQUEST_UPLOAD_FILE';
export const RECEIVE_UPLOAD_FILE_SUCCESS = 'RECEIVE_UPLOAD_FILE_SUCCESS';
